# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(180, 190, 281, 81))
        self.connectButton.setObjectName("connectButton")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(180, 120, 281, 51))
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.calibrateClosedButton = QtWidgets.QPushButton(self.centralwidget)
        self.calibrateClosedButton.setGeometry(QtCore.QRect(180, 330, 111, 41))
        self.calibrateClosedButton.setObjectName("calibrateClosedButton")
        self.calibrateOpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.calibrateOpenButton.setGeometry(QtCore.QRect(350, 330, 111, 41))
        self.calibrateOpenButton.setObjectName("calibrateOpenButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.statusLabel.setText(_translate("MainWindow", "Disconnected"))
        self.calibrateClosedButton.setText(_translate("MainWindow", "Calibrate CLOSED"))
        self.calibrateOpenButton.setText(_translate("MainWindow", "Calibrate OPEN"))
